language: node_js
node_js:
  - "8"
before_script:
  - npm install -g gulp-cli
script: gulp --deploy
deploy:
  - provider: npm
    skip-cleanup: true
    email: "underscript@feildmaster.com"
    api_key: $npm_token
    on:
      tags: true
      branch: master
  - provider: releases
    skip_cleanup: true
    api_key: $github_token
    on:
      tags: true
      branch: master
  - provider: script
    skip_cleanup: true
    script: scripts/gist.sh dist/undercards.user.js
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != master
